name: 🔨CI
on:
  push:
    branches:    
      - '**'
  pull_request:
    branches:    
      - '**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          npm install --location=global npm@latest typescript@latest markdownlint-cli@latest
          npm ci
      - name: Lint
        run: |
          npm run lint
          npm run mdlint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          npm install --location=global npm@latest typescript@latest
          npm ci
      - name: Test
        run: |
          npm run build
          npm run sync
          npm run test
